### ISSUE TITLE
分享失败 读取不到资源

### ISSUE THREAD

**Issue by YzAndroid** [baishixian/Share2#1]
用demo文件选择器的 uri 和自己传路径 生成的uri不一样
manifest 或者其他位置需要配置吗

**Comment by baishixian** [comment]
自己传路径是指直接传 File Path 吗，你先调用 FileUtil. getFileUri 方法获取要分享文件的 Uri 后再传入。

**Comment by YzAndroid** [comment]
new Share2.Builder(this)
                .setContentType(ShareContentType.IMAGE)
                .setShareFileUri(FileUtil.getFileUri(this,ShareContentType.IMAGE,new File(filePath)))
                .setTitle("Share Image")
                .build()
                .shareBySystem();

我现在分享图片 是这样写的 但是分享就会出现找不到文件  file path可以确定是正确的
