### ISSUE TITLE
分享回调监听拿不到状态

### ISSUE THREAD

**Issue by chenyang2580** [baishixian/Share2#4]

**Comment by baishixian** [comment]
有没有调用 setOnActivityResult 方法来设置 onActivityResult 的回调？

**Comment by chenyang2580** [comment]
设置了，然后分享QQ 或者微信之后 onActivityResult 拿Intent一直都是空的 我是分享的一张图片

**Comment by baishixian** [comment]
@chenyang2580 你应该关注 onActivityResult  返回的 requestCode 参数是不是自己传递过去的就行了，分享返回的 Intent 因为没有数据需要回传，所以 Intent 是 null 也没错。
